apiVersion: apps/v1
kind: Deployment
metadata:
  name: football-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: football-app
  template:
    metadata:
      labels:
        app: football-app
    spec:
      containers:
        - name: football-container
          image: zarkk/football-scores-app:v1
          ports:
            - containerPort: 80