apiVersion: v1
kind: Service
metadata:
  name: football-service
spec:
  type: NodePort
  selector:
    app: football-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007